### ISSUE TITLE
No module named torch

### ISSUE THREAD

**Issue by khalilo** [NVlabs/dlinputs#1]
@tmbdev 
How to use this library?
I installed but when I did import dlinputs, I have this error:

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dlinputs/__init__.py", line 6, in <module>
    import shardwriter
  File "/usr/local/lib/python2.7/dist-packages/dlinputs/shardwriter.py", line 16, in <module>
    import torch
ImportError: No module named torch**

I install torch framework, but I have the same error.

**Comment by tmbdev** [comment]
You need to install PyTorch separately; it's not listed in requirements.txt because there are multiple versions depending on your environment.

https://pytorch.org/
